baseURL = "https://www.jamescampbell.us/"
languageCode = "en-us"
title = "Causes & Effects"
defaultContentLanguage   = "en"
isMultilingual           = false
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
googleAnalytics          = "G-1S64X1L3QD"                    # Tracking code, eg. "UA-30108845-1"
# rssLimit = 30
copyright = "2022 James Campbell All rights reserved"

[author]
	name = "James Campbell"
	email = "james@jamescampbell.us"

[params]
    dateform             = "Jan 02, 2006"
    dateformfull         = "Jan 2 2006 15:04:05 EST"
    favicon              = "favicon.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "All rights reserved © 2012-2022"

# Metadata for Open Graph and Twitter
    description          = "James Campbell website pushing buttons since 1981."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Causes & Effects"
    rss                = "index.xml"

[[params.videoBackground.sources]]
    source  = "/sample_video.mp4"
    type    = "video/mp4"
    poster  = "/background.png"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[[params.mainMenu]]
    link = "posts"
    text = "posts"

[[params.mainMenu]]
    link = "shop"
    text = "shop"

[[params.mainMenu]]
    link = "portfolio"
    text = "portfolio"

[[params.mainMenu]]
    link = "about"
    text = "who is james?"

[[params.mainMenu]]
    link = "https://www.jamescampbell.us/index.xml"
    text = "rss"

[imaging]
    quality = 80    
